### ISSUE TITLE
broken atom/rss links for type and properties equals software series

### ISSUE THREAD

**Issue by FennNaten** [ploeh/ploeh.github.com#225]
Hi,
I follow your blog through an RSS reader, and I remarked that the feed links for posts of the latest series (which is pretty interesting by the way) all give a 404.  
I made a quick check, and this seems to be an issue with url generation: actual reachable urls are all made with single dashes between words, while RSS-exposed ones have double dashes replacing the plus sign and equal sign of your titles.  
reachable url: http://blog.ploeh.dk/2016/02/12/types-properties-software-properties-for-the-advantage-state/  
ATOM/RSS item url: http://blog.ploeh.dk/2016/02/12/types--properties--software-properties-for-the-advantage-state
I don't know if you're aware of the issue or not, so I wanted to let you know.
Regards.

**Comment by ploeh** [comment]
Thank you for drawing my attention to this issue, which I wasn't aware of.

This is most likely connected to [GitHub Pages' recent upgrade to Jekyll 3](https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0).

I'll investigate this particular issue when I have time, but I'm no Jekyll or Ruby expert, so if anyone reads this, and think they can help, I'd appreciate it.

**Comment by ploeh** [comment]
When I look at http://blog.ploeh.dk/rss.xml, the most recent article is linked like this:

```XML
<link>
http://blog.ploeh.dk/2016/02/12/types-properties-software-properties-for-the-advantage-state/
</link>
```

This URL seems to be perfectly reachable. It's not the URL you've reported, though.

The URL you've reported _is_ present in the RSS feed, but in the `<guid>` element; you can't expect this value to be a URL, let alone a valid URL.

The same goes for http://blog.ploeh.dk/atom.xml. The link is provided in a `<link>` element:

```XML
<link rel="alternate"
      type="text/html"
      href="http://blog.ploeh.dk/2016/02/12/types-properties-software-properties-for-the-advantage-state/"/>
```

Again, the link you are reporting is the `<id>` field, which you should treat as an opaque identifier - not as a URL.

**Comment by FennNaten** [comment]
Hum, you're right.  
I'm using feedly to manage my subscriptions when on a browser. The subscription points to the right url, and the target xml is as you described it. However feedly seems to use the guid instead of the link, even for the link-sharing functionalities.  
Seems like a bug on feedly side, not on your end, sorry for the disturbance, I should have checked the source directly instead of relying on what's provided on the interface.

**Comment by FennNaten** [comment]
Before contacting feedly to fill a bug report, I checked the RSS spec (as it seems that feedly only uses the RSS file for this blog), and contrary to what I expected, it seems that depending on the interpretation of this spec feedly's behavior can be correct.  
http://cyber.law.harvard.edu/rss/rss.html#ltguidgtSubelementOfLtitemgt  
  
> If the guid element has an attribute named "isPermaLink" with a value of true, the reader may assume that it is a permalink to the item.  
> isPermaLink is optional, its default value is true.  
  
I didn't know that, and it feels odd, but it's consistent with atom specs which states that ids must be valid, stable, rfc3987 IRI.

Learning things everyday. ^^'

**Comment by ploeh** [comment]
Good research work :+1:  I didn't know that.

It seems that the correct resolution to this issue would be to add the attribute `isPermaLink="false"` to the `guid` element. Do you agree?

**Comment by FennNaten** [comment]
Hi,
I think this should do the trick, according to the spec, however it's still a bit of guesswork hoping that feedly follows it. ^^'  
In fine, it depends mostly on what you want to express in your feed, adding this would clearly show that you don't guarantee this guid to be a valid link.

**Comment by ploeh** [comment]
OK, the change is now live. It may take a while before it propagates through all caches.

**Comment by FennNaten** [comment]
Tested, I confirm that feedly now uses the data from the link tag and not anymore the data from the guid tag, for both display and social share.

**Comment by ploeh** [comment]
Sounds good. Thank you for providing feedback. Can we close this issue, then?

**Comment by FennNaten** [comment]
Sure! Thanks for your time.
