### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by haruair** [ploeh/ploeh.github.com#280]
I recently read through your DI posts and it helps me a lot. Thanks for the great articles.

I want to translate these posts to Korean and post it into my personal blog, haruair.com. I couldn't find any policy of translation or redistribution. May I translate these posts and post it? I will put the reference URL clearly. Please let me know if there is any guidance for it.

Hope you have a good day.

**Comment by ploeh** [comment]
Hi, thank you for writing, and for your interest in translating some of my blog posts to Korean. Translation is, in my opinion, fair use, so please go ahead under the following conditions:

- Proper attribution is required. It must be clear to the reader that I'm the original author.
- There should be a link to the original article.
- The translator (you) should be clearly indicated as well.

As an example, for my latest blog post, it could go something like this:

_By Mark Seemann. Translated from [A reusable ApiController Adapter](http://blog.ploeh.dk/2017/03/30/a-reusable-apicontroller-adapter) by Edward Kim_ (but obviously in Korean instead).

**Comment by haruair** [comment]
I will put the reference following your guidance. I will let you know when I post it. Thank you so much!

**Comment by haruair** [comment]
I just post the first one. http://www.haruair.com/blog/3880 I will translate few more. Thanks again!
