### ISSUE TITLE
Too lazy for PR: ad current blog article about C# test data generation via Functor

### ISSUE THREAD

**Issue by drauch** [ploeh/ploeh.github.com#317]
Have you checked out https://github.com/Inspyro/Farada - it looks a lot like your idea of creating a general-purpose test data generator.

**Comment by ploeh** [comment]
I haven't. It's an old idea that [dates back to at least 1999](https://en.wikipedia.org/wiki/QuickCheck).

**Comment by ploeh** [comment]
This discussion seems to be over, so I'm going to close it. Feel free to respond even though it's closed.
