### ISSUE TITLE
Design patterns book suggestion

### ISSUE THREAD

**Issue by chrisregnier** [ploeh/ploeh.github.com#319]
Regarding your blog http://blog.ploeh.dk/2017/10/04/from-design-patterns-to-category-theory/ , if you haven't read Jason Smith's Elemental Design Patterns (https://www.amazon.com/Elemental-Design-Patterns-Jason-Smith/dp/0321711920) then I highly suggest you do. It's all about deconstructing design patterns into more elementary parts (basically the relationships between objects), and I think it fits perfectly with your series.
One thing to note is that it is based on the notion of objected oriented programming, so I would be very interested in seeing a similar breakdown on more functional programming patterns. I suspect there's another dimension of relationships that can be gleaned from a functional lens but I haven't given it much thought myself.

Definitely looking forward to your series.

PS. PR's are too much effort to try to leave a comment (although I imagine it would cut down on useless posts). Just a suggestion but providing an input box on each page and automatically posting a PR through a button (requiring logged in github users), may lower the barrier to entry and allow more discussion on these topics.

**Comment by Hettomei** [comment]
I totally agree with the 'ps' part.

**Comment by ploeh** [comment]
Thank you for the book recommendation. I haven't read that book, but I've added it to my _to-read_ list.

Regarding your suggestion of having an input box that automatically posts a PR, that sounds like an intriguing idea. How would you program something like that?

**Comment by chrisregnier** [comment]
That's a very good question! Not sure off hand, but a quick search and I found this https://developer.github.com/v3/ and quickly tested https://api.github.com/users/ploeh/repos and got results. There's apparently REST APIs for PRs, comments, and all sorts of stuff.

So here's an idea off the top of my head (so I'm sure I'm missing things).
- For each article you write, create an associated issue. (Might want to close it right away as well if you don't like clutter)
- Then you'll have to update your blog as follows:
1.  You'll probably want some test to see if the viewer is logged into github (prob a simple request like the one I posted above. If there's an error you show a github login link, otherwise show the list of comments on the associated issue, along with a comment box.
2. When the user presses the comment button, you can submit a comment directly to the associated issue, and it should create a comment from the specific user.

This is slightly different than using PR's obviously, and unfortunately requires viewers to be logged in to github to see comments, so it may not be a great idea, but hey I'm just pulling things out of the air here :) With a bit of thought I'm sure you can find some other creative ideas; and possibly something that does properly submit a PR so comments can be seen w/o logging in

**Comment by ploeh** [comment]
Closing this issue, as the discussion seems to have died out. Feel free to write if there's more to say; I can always reopen the issue if required.
