### ISSUE TITLE
dependency injection in javascript using composition root

### ISSUE THREAD

**Issue by takion** [ploeh/ploeh.github.com#349]
Hello,

I would to thank you for your great writing on composition root design pattern
and I'll be glad If you could add the content of this link
https://plus.google.com/108617450837535451203/posts/HXUKtQ2nSNg
as a comment for
http://blog.ploeh.dk/2011/07/28/CompositionRoot/

I wrote my own JavaScript Dependency Injection Framework called Di-Ninja wich is, as I know, the only one in javascript that implement the Composition-Root design pattern and it's documentation could be another good example to demonstrate how it works.
https://github.com/di-ninja/di-ninja

**Comment by ploeh** [comment]
Done: http://blog.ploeh.dk/2011/07/28/CompositionRoot

**Comment by takion** [comment]
Many thanks !
