### ISSUE TITLE
More tags

### ISSUE THREAD

**Issue by ploeh** [ploeh/ploeh.github.com#389]
[The tag cloud](http://blog.ploeh.dk/tags) on the blog is becoming increasingly useless, since everything I write today basically just gets shoved into the _Software Design_ tag, which, at the time I'm writing this, has 172 entries. This is clearly not an aid to readers who try to navigate the blog.

While I'll keep the tags that are already present, I'd like to add some more tags that could offer more granular navigation. The intent is to retrofit such tags unto existing articles.

I can't figure out which tags to create, though!

With this issue, I hereby solicit suggestions.

New tags ought to cover more than a pair of articles. I admit that I've made some mistakes when I originally created some of the tags. For example, I thought I'd be writing more on _WPF_ than I ultimately did; that tag only has two entries, but at least that's better than the _Sync_ and _Albedo_ tags.

New tags should have more entries than that (at least 5-10). Additionally, any new tags should be distributed across articles that aren't otherwise natural clusters. For example, one could easily invent a _Monoid_ tag and add it to all the articles in the [Monoids](http://blog.ploeh.dk/2017/10/06/monoids) article series, but if that tag doesn't apply outside of that article series, then what value would it add? That's the reason I haven't already added _Monoid_, _Functor_, or _Category Theory_ tags.

If you have an idea for one or more tags that could be added to the blog, please add your suggestion below, preferably with some suggested articles that'd belong to the new tag.

Better yet, send your suggestion as a pull request 😉

**Comment by adamchester** [comment]
Why do you increasingly keep adding to just the “Softward design” tag?

**Comment by ploeh** [comment]
That's my issue! Which other tag(s) do you think I should use for my recent articles?

**Comment by ploeh** [comment]
I've now added a [Design Patterns](http://blog.ploeh.dk/tags/#Design%20Patterns-ref) tag. It spans articles from 2010 to 2018, and I have two more articles with that tag queued up for publication in 2019. It already includes 26 articles, so I think it fits all the above criteria.

**Comment by PraveenTalari** [comment]
Could you please add new header called "Series" to
http://blog.ploeh.dk/tags/

with links to series such as
http://blog.ploeh.dk/2017/10/04/from-design-patterns-to-category-theory/

BTW, do you have any other series of articles as such?

**Comment by ploeh** [comment]
@PraveenTalari that sounds like a good idea, but I wonder about the 'implementation details'. Do you have in mind that _all_ the posts that belong to a series should be so tagged, or only the introductory article that contains a table of contents? An example would be, as you provide it, http://blog.ploeh.dk/2017/10/04/from-design-patterns-to-category-theory

**Comment by PraveenTalari** [comment]
@ploeh

only introductory article is fine.

if such series are only 1 or 2, we can keep sub articles as sub headings with or without links.

**Comment by ploeh** [comment]
@PraveenTalari That fits my preference as well.

A few follow-up questions:

How about articles such as http://blog.ploeh.dk/2017/10/06/monoids or http://blog.ploeh.dk/2018/03/22/functors ? These are already part of the overall http://blog.ploeh.dk/2017/10/04/from-design-patterns-to-category-theory article, but are themselves 'sub series'. Should they be tagged as well, or is it just the top article?

It seems to me that the main benefit of a tag like this is to be able to quickly identify the entry points of various series. Is the purpose rather to find a series' _table of contents?_

I wonder which tag name best addresses those concerns:

- Series
- Article Series
- Table of Contents
- Series Table of Contents
- Article Series Table of Contents
- [something else?]

Between those, I have my own preference, but I'd like to know what you prefer as well.

**Comment by PraveenTalari** [comment]
In my opinion, sub series should NOT be tagged as "SERIES". Tagging such sub series will bloat and that  is the main reason this issue got created.

**"Is the purpose rather to find a series "table of contents" ?** -  Yes.

My favorite title is "Series".

"Series" - simple and straight to the point.

"Article series" - verbose and not more abstract. You cannot add a video URL of your conference talk if you feel that it should be viewed at the end of a particle sub series. For example: "Get value out of your monad - Mark Seemann" Youtube URL can be added at the end of "Monad" sub series.

"Table of Contents" - looks fine but I feel it is not suitable here. As it is generally used for "totality", there shouldn't be a article on your blog which is not part of this.

Right now what I can imagine is
SERIES:
1. from-design-patterns-to-category-theory
     Monoids, semigroups, and friends
         Monoids
             Angular addition monoid
             Strings, lists, and sequences as a monoid
2. ___________

This also motivates you to write new series of articles.

**Comment by ploeh** [comment]
@PraveenTalari, I'm still not entirely sure if we agree on the minute details, but instead of talking _about_ doing something, it might be more productive to _do_ something, and then discuss that 😄 

I have, therefore, created [a pull request](https://github.com/ploeh/ploeh.github.com/pull/454) that embodies my interpretation and preferences for this feature. Feel free to leave a review 😉 

As you can see, I lean towards calling the tag _Article Series_. This tag should work for other readers, and I'm concerned that a tag simply named _Series_ would be too obscure. Is it about time series programming? Naming it _Article Series_ makes it, I hope, slightly clearer that this tag identifies an article series.

When rendered, this pull request produces the following tag:

![image](https://user-images.githubusercontent.com/242165/52956821-88816780-3390-11e9-8c30-6879f178b2b3.png)

**Comment by PraveenTalari** [comment]
So you too feel that - "we should not include sub series" ?

Article Series - works for most people :thumbsup:

**Comment by ploeh** [comment]
> So you too feel that - "we should not include sub series" ?

That seems reasonable to me. Wasn't that what you wanted?

FWIW, the tag is [now live](http://blog.ploeh.dk/tags/#Article%20Series-ref).

**Comment by PraveenTalari** [comment]
Yes :relaxed:

**Comment by ploeh** [comment]
I'm wondering if it would make sense if I add a _Domain-Driven Design_ tag... I don't think that I explicitly discuss DDD much, but on the other hand, I seem to be often skirting DDD-like topics.

I admit that this is, at the moment, just a stray thought. I haven't even looked through my articles to see if there's a critical mass of them to warrant this tag. I also wonder if there'd be substantial overlap with the [Software Design tag](https://blog.ploeh.dk/tags/#Software%20Design-ref).

**Comment by PraveenTalari** [comment]
**"I don't think that I explicitly discuss DDD much, but on the other hand..."**

I feel that marking existing articles DDD because they consist of DDD-like topic backfires.

You can start a separate series of articles(can be very small) with DDD tag and can point URLs old relevant articles.

One more negative point is that major part of the existing existing article is written with a different the intention when it was written which is very much different from what the DDD tag stands for.

**Comment by ploeh** [comment]
FWIW, I've now added a [Code](https://blog.ploeh.dk/tags/#Code-ref) tag. The intend is that this tag identifies articles that discuss _code_ - how it's laid out, how variables are named, etc.

It's not a big tag, but it has articles sufficiently spread over the entire history of the blog (including two in queue) to warrant its existence, I think.

With this tag, I'm going to close the issue. If you have suggestions for new tags, please comment here, even though the issue is now closed.
