### ISSUE TITLE
"Beyond Church encoding: Böhm-Berarducci isomorphism of algebraic data types (...)"

### ISSUE THREAD

**Issue by freddie-freeloader** [ploeh/ploeh.github.com#391]
Hey!

Thanks for your article on "Church-encoded Maybe"! :slightly_smiling_face: 

Are you aware of Oleg Kiselyov's writings on that topic? [This page](http://okmij.org/ftp/tagless-final/course/Boehm-Berarducci.html) provides an introduction and collections of his ideas on *Typed Church-encoding* aka *Böhm-Berarducci-encoding*. Reading this was quite an eye opener for me and a great inspiration. :smiley:

Cheers!

**Comment by ploeh** [comment]
I wasn't, but thank you for sharing 👍
