### ISSUE TITLE
Print version

### ISSUE THREAD

**Issue by HyShai** [ploeh/ploeh.github.com#421]
Would it be possible to get a better print.css? Currently the print version includes extraneous sections (comments/buttons/footers).

**Comment by ploeh** [comment]
I think that sounds like a reasonable request. I am, however, almost entirely ignorant of modern front-end development, so I'm not likely to take this on by myself, unless someone convinces me that it's way easier than I currently fear that it is.

I'll be happy to consider a pull request, though 😉

**Comment by giuliohome** [comment]
Modern frontend development is so fundamental to moden development! When I see people reasoning about monad transformers and tagless final I'm afraid they are missing an important point, which is what IO prematurely abstracts out... From a theoretical point of view, Bootstrap is an object-oriented CSS framework and that makes it so widely adopted and, ultimately, it's why the UI of these pages is easy to maintain for you by means of a simple PR .
