### ISSUE TITLE
File name containing either-bifunctor post "wrong"

### ISSUE THREAD

**Issue by bender2k14** [ploeh/ploeh.github.com#424]
The file containing your Either bifunctor post has the "wrong" file name.  Instead of `2018-01-07-either-bifunctor.html` it should be `2019-01-07-either-bifunctor.html` (i.e. the year should be `2019` instead of `2018`).

**Comment by ploeh** [comment]
Thank you for letting me know 👍 

This occasionally happens to me, particularly around new year 😳 If you're curious and look into the Git history, you'll see that often, quite some time go by from I write an article until I actually publish it. This one, obviously, was written in 2018.

Fortunately, the date part of the URL is generated from the front matter, and not the file name, so fixing the issue isn't a breaking change 😌 

I've fixed it now.
