### ISSUE TITLE
Enforce HTTPS

### ISSUE THREAD

**Issue by ploeh** [ploeh/ploeh.github.com#430]
Several people have, with accumulated effort, convinced me that I should turn on HTTPS for the blog.

Currently, the blog is hosted by _GitHub pages_, which it has been for a long time, so unless I want to move it, I'm able to do whatever GitHub pages allow me to do.

For some time now, HTTPS has already been enabled as opt-in. Thus, https://blog.ploeh.dk actually works. On the other hand, HTTPS isn't enforced. It probably should be.

One critical requirement is that old links must still work. There's quite a few links to various articles on the blog, from various sources that I don't control, and those should still work. If I read the [GitHub pages documentation on enabling HTTPS](https://help.github.com/articles/securing-your-github-pages-site-with-https/) correctly, this should automatically work with redirects. It remains to be seen, though.

Before I turn on that feature, however, the source for the blog should be scanned for mixed content, as also outlined in the above documentation. That could be a non-trivial task.

**Comment by ghuntley** [comment]
Looks like I owe you 1 x 🍻

**Comment by ploeh** [comment]
FWIW, I made the switch yesterday and [told people to report any issues](https://twitter.com/ploeh/status/1103273067181195264). No complaints so far, so perhaps it's just worked...

I'm skeptical that it could really have been that easy 🤔

**Comment by ploeh** [comment]
I should probably do a search-and-replace on all the internal links on the blog... 😓

**Comment by ghuntley** [comment]
Done it for you over at https://github.com/ploeh/ploeh.github.com/pull/457

**Comment by ploeh** [comment]
@ghuntley, I think that counts for 🍻! Thank you so much!
