### ISSUE TITLE
Comment on title: "Code readability hypotheses" could not push a new branch.

### ISSUE THREAD

**Issue by arturohernandez10** [ploeh/ploeh.github.com#449]
I could not push a new branch for this comment.

	<div class="comment" id="fef627676986467bbbee0f60cb38707d">
		<div class="comment-author"><a href="https://www.clearlaunch.com/meet-the-team/">Arturo Hernandez</a></div>
		<div class="comment-content">
			<p>
				There is a huge problem in the way that we evaluate software quality. Karsten, is naming many of the reasons that make it difficult. But given that it is difficult, The only rational way to solve it without relying as heavily credentials, personality and repetition. Is to establish guidelines and have multiple opionins/measurements of code samples. 
			</p>
			<p>
				I think we overvalue experience in evaluating code. And in the contrary, there are real issues with expert bias, particularly of older programmers who have good credentials but are more financially and emotionally invested in a particular technology. In general, it is much more difficult to write good code, than to read it. Therefore, most programmers can read, understand and appreciate good code. While they may not have been able to write from scratch themselves. The only exception would be for true neophytes (which there may be ways to exclude). We also need to be leary about software qualities that are hard to grasp and evaluate. Unexplainable or unclear instinct can lead to bad outcomes.
			</p>
			<p>
				There is real oportunity here to more scientifically quantify aspects of code quality. I wish more people devoted time to it.
			</p>
		</div>
		<div class="comment-date">2019-02-14 17:36 UTC</div>
	</div>

**Comment by ploeh** [comment]
No worries, I've copied the text and added it myself: http://blog.ploeh.dk/2013/03/04/code-readability-hypotheses/#fef627676986467bbbee0f60cb38707d

This way of commenting works as well, but if you're interested in being able to submit a pull request in the future, is there anything I can do to help you?

You can, indeed, not push to this particular repository; I'm the only one who can do that. You can, however, [fork the repository](https://help.github.com/articles/fork-a-repo/), make changes to your fork, and then submit a [pull request](https://help.github.com/articles/about-pull-requests/). Please accept my apologies if I told you something you already knew.

**Comment by ploeh** [comment]
I'll close this issue for now; that doesn't imply that you can't post more comments to it. I can even reopen it if necessary. Let me know if this gives rise to any concerns.
