### ISSUE TITLE
Broken link to Pluralsight course

### ISSUE THREAD

**Issue by bender2k14** [ploeh/ploeh.github.com#493]
[This post](https://blog.ploeh.dk/2016/01/18/make-pre-conditions-explicit-in-property-based-tests/) ends with a broken link to one of your Pluralsight courses.  Maybe this is a temporary problem.  In any case, here is the error message that I get.

> The link is not currently active.
> 
> There are a number of reasons that you may have received this message. The most common is that the merchant who was advertising is temporarily not-actively promoting that program. If, however, you feel you have reached this page in error, please let us know. Shareasale.com does not tolerate or send any SPAM mail to anyone. If you feel you have been targeted by a SPAM message, we would appreciate if you could forward the message to us at abuse at shareasale.com.
> 
> Shareasale.com manages the relationships between advertisers and affiliates, which is why you were directed to our site. Since the link that you clicked is not currently active, you were not redirected to the site. 
> 
> If you are a new affiliate, your links will not be active until Shareasale.com gets a chance to review your account - you will receive an email when your account is approved and links are activated. This process generally takes around 24 business hours.

**Comment by ploeh** [comment]
Thank you for bringing this to my attention 👍  That URL had somehow escaped my attention, but I've now corrected it.

**Comment by ploeh** [comment]
I think I'll go out on a limb and presume that I've addressed the issue. I'll therefor close it.

Please feel free to reopen it if it still needs my attention.

**Comment by bender2k14** [comment]
Oh, yes. It works for me now. Thanks! Sorry for my delay in saying so.
