### ISSUE TITLE
Do we make up comment/heading IDs ourselves?

### ISSUE THREAD

**Issue by cmeeren** [ploeh/ploeh.github.com#511]
When sending a PR for adding a comment, are we supposed to randomly make up the comment ID (and any comment heading IDs) ourselves?

Also, is there a simple way to format code with syntax highlighting?

**Comment by ploeh** [comment]
The comment ID is just a GUID, which [you can easily create yourself](https://www.uuidgenerator.net). If you don't want to do that, however, I'll do it for you when I merge.

The way I format code with syntax highlighting is that I use the [Copy As Html Visual Studio extension](https://marketplace.visualstudio.com/items?itemName=VisualStudioPlatformTeam.CopyAsHtml). If you don't want to do that, you can just surround your code with `<pre>` tags; it's just HTML.

**Comment by cmeeren** [comment]
Thanks for the clarifications!
