### ISSUE TITLE
Dim code body unless mouse hovers over it

### ISSUE THREAD

**Issue by ploeh** [ploeh/ploeh.github.com#534]
There's been a bit of confusion about my article [Zone of Ceremony](http://localhost:4000/2019/12/16/zone-of-ceremony). My intention was to discuss the _ceremony_ required with various languages, i.e. [what you have to do before you get to do what you really want to do](https://twitter.com/andreas_dorfer/status/1206666063691292672).

Creating files for classes, defining classes, and declaring types is, as I see it, a big part of this. _How_ the actual implementation code looks was never my point.

I debated with myself whether to even show any code. My point was the _Zone of Ceremony_ concept and the idea about _trans-ceremonial languages_. I thought, however, that if I didn't show any code, the article would be too abstract.

I also debated whether to just show method/function declarations without the implementation code. For example, I could have showed the C# example like this:

```csharp
public static class Enumerable
{
    public static IEnumerable<int> Consume(
        this IEnumerable<int> source,
        int quantity)
    {
        // Implementation goes here...
    }
}
```

I was concerned, however, that this would also confuse some readers. Particularly, when you'd reach the F# and Haskell examples, you be presented with a Haskell example like this, which looks almost disingenuous to the uninitiated:

```haskell
consume quantity = -- Implementation goes here...
```

So I decided to include all of the code.

I also decided to go with what I considered most idiomatic for the language in question. I wrote the C# code as a _for_ loop, while I wrote the F# and Haskell examples using a _fold_. (I've no idea what's idiomatic in JavaScript, but I used a _for_ loop there as well.)

The result of those decisions was that some readers interpreted the article as extolling the virtues of _folds_ over _for_ loops, which wasn't my point at all.

I'd like to de-emphasise the implementation code while still keeping it around. Ideally, I'd like the method/function bodies to be greyed out by default, like this:

![image](https://user-images.githubusercontent.com/242165/70972689-368a9a80-20a4-11ea-9ae1-c3f38e0bc7d4.png)

If you want to see the method body, you'd mouse over the `pre` element, and it'd light up with all the colouring that it currently has.

I'd like this implemented with the least amount of new 'code' for the site, i.e. not too much new JavaScript or CSS. It's basically an ad-hoc adjustment for this particular article.

**Comment by barisere** [comment]
Being an ad-hoc adjustment for only one article, how about an update to the article, commenting out the implementation, and a note explaining that the implementation code doesn't matter?
```js
function consume (source, quality) {
  // if (!source) {
  //  return [];
  // }
  // let accumulator = 0;
  // const result = [];
  // ...
}
```

**Comment by ploeh** [comment]
@barisere, thank you for that suggestion 👍 At first, I didn't like it, but then the suggestion grew on me. Now, I'm perhaps a bit over my greatest enthusiasm. It'd certainly be a simple solution, but now I'm concerned it'll confuse some readers - even if I leave an explanatory note in the text, lots of readers don't actually _read_ it 🙄

**Comment by barisere** [comment]
@ploeh that's certainly a problem. I think using typography to emphasize the explanatory text can help, especially if the text is placed close enough to the first block of code.
My concern is that, because you're not using a custom template for your blog (are you), extending the current one may be more work than necessary to achieve the goal. Can we can extend your blog theme with some custom CSS styles and a sprinkle of JavaScript? :thinking:

**Comment by ploeh** [comment]
Manipulating the HTML is definitely an option.

**Comment by ploeh** [comment]
I decided to just dim the method bodies, with no interactivity. It's live now.

**Comment by bender2k14** [comment]
> I'd like to de-emphasise the implementation code while still keeping it around. Ideally, I'd like the method/function bodies to be greyed out by default...

I will soon have a blog hosted by `coding.blog`, which displays it's code using codedoc.  It doesn't have the ability to dim lines like you specifically asked, but it can do the opposite; it can [highlight specific lines](https://codedoc.cc/docs/code/highlights).
