### ISSUE TITLE
Better word for pure DI

### ISSUE THREAD

**Issue by inf3rno** [ploeh/ploeh.github.com#540]
You write here that you don't like the pure DI term: https://blog.ploeh.dk/2014/06/10/pure-di/
In javascript we have the word "vanilla", which means exactly what you are looking for. It is solving something without frameworks.

**Comment by inf3rno** [comment]
> "VanillaJS is a name to refer to using plain JavaScript without any additional libraries like jQuery. People use it as a joke to remind other developers that many things can be done nowadays without the need for additional JavaScript libraries."

So either "vanilla DI" or "plain DI" should be fine imho.

**Comment by ploeh** [comment]
I like _Vanilla DI!_ I wish I had thought of it when I came up with _Pure DI_...

As my article explains, the term _Pure DI_ was an attempt to introduce a better term than _Poor Man's DI_. While I like _Pure DI_ better than _Poor Man's DI_, that term isn't evocative.

_Vanilla DI_ really captures the essence of keeping it as simple as possible.

**Comment by ploeh** [comment]
As you may or may not have noticed, I [tweeted a link to this issue](https://twitter.com/ploeh/status/1216340959803461634) to solicit reactions. As you can see from the reactions, many people like the term, while other people dislike it. I haven't made the work of classifying and counting all the reactions, but I get the impression that they're mixed.

The most weighty argument against a new term, I think, is that it might be confusing. As [Martin Fowler put it in a different context](https://twitter.com/martinfowler/status/1156944960782028802):

> I prefer to not to rename concepts like this. It usually only adds confusion

I still like _Vanilla DI_, so I may use it in contexts where it fits, but I think I'll keep _Pure DI_ around as the 'formal' term, despite all its flaws.
