### ISSUE TITLE
Date in Bilder isomorphism file name is wrong

### ISSUE THREAD

**Issue by bender2k14** [ploeh/ploeh.github.com#556]
For the [Bilder isomorphism post](https://blog.ploeh.dk/2020/02/10/builder-isomorphisms/), the URL and the time stamp in the article both correspond to the date `2020-02-10`, which is correct, but date in the name of the [corresponding file](https://github.com/ploeh/ploeh.github.com/blob/master/_posts/2020-01-14-builder-isomorphisms.html) is `2020-01-14`.

**Comment by ploeh** [comment]
Thank you for pointing that out to me. It happens occasionally that I forget to correct the file names, but fortunately doing so after the fact isn't a breaking change.

I've corrected the name now.
