### ISSUE TITLE
Interpretations of quantum mechanics

### ISSUE THREAD

**Issue by TysonMN** [ploeh/ploeh.github.com#616]
Quoting [The IO Container](https://blog.ploeh.dk/2020/06/08/the-io-container/)
> The many-worlds interpretation
>...
> Only when you observe the contents of the box does the superposition collapse to a single value.

That phrase describes the [Copenhagen interpretation of quantum mechanics](https://en.wikipedia.org/wiki/Interpretations_of_quantum_mechanics#Copenhagen_interpretation).  In contrast, the [many worlds interpretation](https://en.wikipedia.org/wiki/Interpretations_of_quantum_mechanics#Many_worlds) says that each observation causes the entire universe to split into copies that are identical in every way except for the state of the observation.

**Comment by ploeh** [comment]
Well, yes, I'm in Copenhagen 😉

**Comment by bender2k14** [comment]
Indeed...I also noticed that play on words 😆
