### ISSUE TITLE
[Suggestion] use Utterances for comments

### ISSUE THREAD

**Issue by thomaslevesque** [ploeh/ploeh.github.com#618]
Hi Mark,

Your README says

> As an experiment, all comments for a particular post are kept as part of the post itself.
> 
> If you wish to comment on a particular post, send me a pull request for that post. If you're in doubt about the format, just look at how previous comments are formatted. For an example of a post with comments, see e.g. [the very first post on this blog](/_posts/2009-01-28-LivingInInterestingTimes.html).

This "experiment" has been going on for years. In my opinion, this process is a major impediment to commenting on your blog. Many times, I wanted to comment, but never did because I didn't want to go through the hassle. I suspect many of your readers have the same experience.

If I may offer a suggestion: using something like [Utterances](https://utteranc.es/) for comments would make commenting much easier. I recently started using it on my own blog, and the integration is extremely easy (I use Hugo, but the experience should be similar with Jekyll). It uses Github issues, so you don't need to subscribe to a third-party service. Commenters need a Github account, which suppresses most of the spam.

**Comment by ploeh** [comment]
Please accept my apologies for not reacting to this post before now. It must somehow have slipped under my radar.

In a similar GitHub issue, I today [explained why I'm not inclined to rely on more external services than strictly necessary](https://github.com/ploeh/ploeh.github.com/issues/661#issuecomment-698429830). I think that this suggestion falls in the same category.

**Comment by thomaslevesque** [comment]
Hi Mark,

Thanks for your answer. I understand your reasons, even though I don't fully agree with them. I just wish commenting on your blog involved a bit less effort... But maybe I'm just lazy!

Anyway, thanks for your great articles, keep up the good work!

**Comment by ploeh** [comment]
To be clear, I realise that the system isn't _ideal,_ but I find that it adequately addresses most of my concerns. And yes, I also understand that it does that by shifting some of the burden to people who want to comment 😄

**Comment by thomaslevesque** [comment]
In fact, I have a different idea: add a comment form that creates a PR on the article, with the comment in the right place. This way, the comments stay in the article itself, but commenting is easier. I have no idea how hard it would be to implement, though...

**Comment by ploeh** [comment]
That's closer to something that could work.

What I'd really like to have is comments as separate files, but with enough metadata that the static site renderer could weave them into the article in the correct order. It could be combined with your idea, as far as I can tell. The problem is, though, that if there's a way to make Jekyll do that, I'm not aware of it.

**Comment by thomaslevesque** [comment]
It *might* be possible... https://jekyllrb.com/docs/includes/#including-files-relative-to-another-file
