### ISSUE TITLE
Forward links to impureim sandwich

### ISSUE THREAD

**Issue by TysonMN** [ploeh/ploeh.github.com#716]
[You used the phrase "impure/pure/impure sandwich" many times](https://github.com/ploeh/ploeh.github.com/search?q=%22impure%2Fpure%2Fimpure+sandwich%22) before dedicating an entire post to it titled [Impureim sandwich](https://blog.ploeh.dk/2020/03/02/impureim-sandwich/).
> Since January 2017 I've been singing the praise of the impure/pure/impure sandwich, but I've never published an article that defines the term. I intend this article to remedy the situation.

What do you think about having those older posts link to this newer article?  A downside with forward links is that it can lead to articles linking to each other in a referencial circle as though each depends on the other.

I am willing to add those links.

**Comment by ploeh** [comment]
That sounds like a good idea 👍
