### ISSUE TITLE
What of streams?

### ISSUE THREAD

**Issue by knz** [ploeh/ploeh.github.com#807]
hi @ploeh 

https://github.com/ploeh/ploeh.github.com/blob/0d90383d31f6eaea00e270629a3bff48f5849571/_posts/2022-05-02-at-the-boundaries-applications-arent-functional.html#L173

So ok applications are not functional and object-oriented at boundaries.

What do you think of modeling programs as *stream processors*?

ie boxes that consume streams of data as input, and produce streams of data as output, possibly concurrently.

This model of computation composes, and given some recursive stream operators is even turing-complete. There are stream-oriented programming languages.

Would you consider applications to still be modelable as stream processors at the boundary? Would stream processing "scale up" to compose applications in the same way as individual components inside applications?

**Comment by ploeh** [comment]
I'm assuming that you're talking about Pipes and Filters architectures as in [EIP](https://blog.ploeh.dk/ref/eip).

What would the boundaries of such an architecture look like? Are they stream-like?

**Comment by ploeh** [comment]
Closing du to inactivity.
