### ISSUE TITLE
Subscribe to the blog?

### ISSUE THREAD

**Issue by DaveInCaz** [ploeh/ploeh.github.com#828]
Forgive me if I overlooked it, though I looked around quite a lot on a few occasions.

Is there any way to subscribe to your blog so that we can be notified of new articles?

Thanks

**Comment by ploeh** [comment]
Yes, there is: https://blog.ploeh.dk/2013/04/09/ploeh-blog-syndication-feed-addresses

**Comment by ploeh** [comment]
See also #76

**Comment by TysonMN** [comment]
What program do you want to use to follow?  I use Feedly and am following this blog.

**Comment by DaveInCaz** [comment]
@ploeh thank you! I did miss that. Maybe it could be easier to find... I think I had previously done a Google search like:

`subscribe: https://blog.ploeh.dk/`

and it didn't turn up. I hadn't looked for "syndication".

@TysonMN Personally I was thinking to get an email when a new article is published.

**Comment by ploeh** [comment]
Yes, I should probably put the word _subscribe_ somewhere, but I wonder how much of a use case it is these days...

FWIW, years ago there was a budding standard for syndication auto-discovery, and each page on the blog actually does come with that metadata:

    
    <link rel="alternate" type="application/rss+xml" href="/rss.xml" title="RSS feed for ploeh blog">
    <link rel="alternate" type="application/atom+xml" href="/atom.xml" title="ATOM feed for ploeh blog">

It never really seems to have made much of a difference, but on the other hand, I never hear from all the people for whom this just works... assuming there are any...

**Comment by ploeh** [comment]
FWIW, I use IFTTT to automatically tweet each new article. You could probably use that to send an email instead.

**Comment by TysonMN** [comment]
There appear to be many RSS-to-email services

**Comment by DaveInCaz** [comment]
Email is not a necessity, just a preference. Thanks for the tips on that!

I wonder if it would be worth adding a new Github "release" for a new blog entry? That is another way people could subscribe.

**Comment by ploeh** [comment]
> I wonder if it would be worth adding a new Github "release" for a new blog entry? That is another way people could subscribe.

That sounds like more work for me...
